// Code generated by eido. DO NOT EDIT.
// Copyright © Kaleido, Inc. 2025

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package platform

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CantonParticipantNodeServiceResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Environment         types.String `tfsdk:"environment"`
	EnvironmentMemberID types.String `tfsdk:"environment_member_id"`
	Runtime             types.String `tfsdk:"runtime"`
	Name                types.String `tfsdk:"name"`
	StackID             types.String `tfsdk:"stack_id"`
	Defaultparty        types.String `tfsdk:"defaultparty"`
	Domainnetworks      types.List `tfsdk:"domainnetworks"`
	Globaldomainnetwork types.String `tfsdk:"globaldomainnetwork"`
	KmsKeymanager       types.String `tfsdk:"kms_keymanager"`
	KmsWallet           types.String `tfsdk:"kms_wallet"`
	Onboardingsecret    types.String `tfsdk:"onboardingsecret"`
	Walletusers         types.List `tfsdk:"walletusers"`
	ForceDelete         types.Bool   `tfsdk:"force_delete"`
}

func CantonParticipantNodeServiceResourceFactory() resource.Resource {
	return &cantonparticipantnodeserviceResource{}
}

type cantonparticipantnodeserviceResource struct {
	commonResource
}

func (r *cantonparticipantnodeserviceResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "kaleido_platform_cantonparticipantnode"
}

func (r *cantonparticipantnodeserviceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"id": &schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"environment": &schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Environment ID where the CantonParticipantNode service will be deployed",
			},
			"environment_member_id": &schema.StringAttribute{
				Computed: true,
			},
			"runtime": &schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Runtime ID where the CantonParticipantNode service will be deployed",
			},
			"name": &schema.StringAttribute{
				Required:    true,
				Description: "Display name for the CantonParticipantNode service",
			},
			"stack_id": &schema.StringAttribute{
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Stack ID where the CantonParticipantNode service belongs (optional)",
			},
			"defaultparty": &schema.StringAttribute{
				Optional:    true,
				Description: "Party Hint for the default party",
			},
			"domainnetworks": &schema.ListAttribute{
				ElementType: basetypes.StringType{},
				Optional:    true,
				Description: "CantonPrivateSynchronizerNetworks",
			},
			"globaldomainnetwork": &schema.StringAttribute{
				Optional:    true,
				Description: "CantonGlobalDomainNetwork",
			},
			"kms_keymanager": &schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "keyManagerService",
			},
			"kms_wallet": &schema.StringAttribute{
				Optional:    true,
				Description: "Wallet name to store the keys",
			},
			"onboardingsecret": &schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "Onboarding secret provided by the super validator",
			},
			"walletusers": &schema.ListAttribute{
				ElementType: basetypes.StringType{},
				Optional:    true,
				Description: "A list of additional wallet users",
			},
			"force_delete": &schema.BoolAttribute{
				Optional:    true,
				Description: "Set to true when you plan to delete a protected CantonParticipantNode service. You must apply this value before running terraform destroy.",
			},
		},
	}
}

func (data *CantonParticipantNodeServiceResourceModel) toCantonParticipantNodeServiceAPI(ctx context.Context, api *ServiceAPIModel, diagnostics *diag.Diagnostics) {
	api.Type = "CantonParticipantNodeService"
	api.Name = data.Name.ValueString()
	api.StackID = data.StackID.ValueString()
	api.Runtime.ID = data.Runtime.ValueString()
	api.Config = make(map[string]interface{})

	if !data.Defaultparty.IsNull() && data.Defaultparty.ValueString() != "" {
		api.Config["defaultParty"] = data.Defaultparty.ValueString()
	}
	if !data.Domainnetworks.IsNull() && len(data.Domainnetworks.Elements()) > 0 {
		var domainnetworksList []string
		for _, elem := range data.Domainnetworks.Elements() {
			if strElem, ok := elem.(basetypes.StringValue); ok {
				domainnetworksList = append(domainnetworksList, strElem.ValueString())
			}
		}
		api.Config["domainNetworks"] = domainnetworksList
	}
	if !data.Globaldomainnetwork.IsNull() && data.Globaldomainnetwork.ValueString() != "" {
		api.Config["globalDomainNetwork"] = data.Globaldomainnetwork.ValueString()
	}
	// Handle kms flattened fields
	kmsConfig := make(map[string]interface{})
	if !data.KmsFolder.IsNull() && data.KmsFolder.ValueString() != "" {
		kmsConfig["folder"] = data.KmsFolder.ValueString()
	}
	if !data.KmsKeymanager.IsNull() && data.KmsKeymanager.ValueString() != "" {
		kmsConfig["keyManager"] = data.KmsKeymanager.ValueString()
	}
	if !data.KmsWallet.IsNull() && data.KmsWallet.ValueString() != "" {
		kmsConfig["wallet"] = data.KmsWallet.ValueString()
	}
	// Set the config if any fields were set
	if len(kmsConfig) > 0 {
		api.Config["kms"] = kmsConfig
	}
	if !data.Onboardingsecret.IsNull() && data.Onboardingsecret.ValueString() != "" {
		api.Config["onBoardingSecret"] = data.Onboardingsecret.ValueString()
	}
	if !data.Walletusers.IsNull() && len(data.Walletusers.Elements()) > 0 {
		var walletusersList []string
		for _, elem := range data.Walletusers.Elements() {
			if strElem, ok := elem.(basetypes.StringValue); ok {
				walletusersList = append(walletusersList, strElem.ValueString())
			}
		}
		api.Config["walletUsers"] = walletusersList
	}
}

func (api *ServiceAPIModel) toCantonParticipantNodeServiceData(data *CantonParticipantNodeServiceResourceModel, diagnostics *diag.Diagnostics) {
	data.ID = types.StringValue(api.ID)
	data.EnvironmentMemberID = types.StringValue(api.EnvironmentMemberID)
	data.Runtime = types.StringValue(api.Runtime.ID)
	data.Name = types.StringValue(api.Name)
	data.StackID = types.StringValue(api.StackID)

	if v, ok := api.Config["defaultParty"].(string); ok {
		data.Defaultparty = types.StringValue(v)
	} else {
		data.Defaultparty = types.StringNull()
	}
	if v, ok := api.Config["domainNetworks"].([]interface{}); ok {
		var domainnetworksElements []attr.Value
		for _, item := range v {
			if str, ok := item.(string); ok {
				domainnetworksElements = append(domainnetworksElements, basetypes.NewStringValue(str))
			}
		}
		if len(domainnetworksElements) > 0 {
			domainnetworksList, _ := basetypes.NewListValue(basetypes.StringType{}, domainnetworksElements)
			data.Domainnetworks = domainnetworksList
		} else {
			data.Domainnetworks = basetypes.NewListNull(basetypes.StringType{})
		}
	} else {
		data.Domainnetworks = basetypes.NewListNull(basetypes.StringType{})
	}
	if v, ok := api.Config["globalDomainNetwork"].(string); ok {
		data.Globaldomainnetwork = types.StringValue(v)
	} else {
		data.Globaldomainnetwork = types.StringNull()
	}
	// Extract kms flattened fields
	if kmsConfig, ok := api.Config["kms"].(map[string]interface{}); ok {
	if v, ok := kmsConfig["folder"].(string); ok {
		data.KmsFolder = types.StringValue(v)
	} else {
		data.KmsFolder = types.StringNull()
	}
	if v, ok := kmsConfig["keyManager"].(string); ok {
		data.KmsKeymanager = types.StringValue(v)
	} else {
		data.KmsKeymanager = types.StringNull()
	}
	if v, ok := kmsConfig["wallet"].(string); ok {
		data.KmsWallet = types.StringValue(v)
	} else {
		data.KmsWallet = types.StringNull()
	}
	} else {
		data.KmsFolder = types.StringNull()
		data.KmsKeymanager = types.StringNull()
		data.KmsWallet = types.StringNull()
	}
	if v, ok := api.Config["onBoardingSecret"].(string); ok {
		data.Onboardingsecret = types.StringValue(v)
	} else {
		data.Onboardingsecret = types.StringNull()
	}
	if v, ok := api.Config["walletUsers"].([]interface{}); ok {
		var walletusersElements []attr.Value
		for _, item := range v {
			if str, ok := item.(string); ok {
				walletusersElements = append(walletusersElements, basetypes.NewStringValue(str))
			}
		}
		if len(walletusersElements) > 0 {
			walletusersList, _ := basetypes.NewListValue(basetypes.StringType{}, walletusersElements)
			data.Walletusers = walletusersList
		} else {
			data.Walletusers = basetypes.NewListNull(basetypes.StringType{})
		}
	} else {
		data.Walletusers = basetypes.NewListNull(basetypes.StringType{})
	}
}

func (r *cantonparticipantnodeserviceResource) apiPath(data *CantonParticipantNodeServiceResourceModel) string {
	path := fmt.Sprintf("/api/v1/environments/%s/services", data.Environment.ValueString())
	if data.ID.ValueString() != "" {
		path = path + "/" + data.ID.ValueString()
	}
	if !data.ForceDelete.IsNull() && data.ForceDelete.ValueBool() {
		path = path + "?force=true"
	}
	return path
}

func (r *cantonparticipantnodeserviceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CantonParticipantNodeServiceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	var api ServiceAPIModel
	data.toCantonParticipantNodeServiceAPI(ctx, &api, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	ok, _ := r.apiRequest(ctx, http.MethodPost, r.apiPath(&data), api, &api, &resp.Diagnostics)
	if !ok {
		return
	}

	api.toCantonParticipantNodeServiceData(&data, &resp.Diagnostics)
	r.waitForReadyStatus(ctx, r.apiPath(&data), &resp.Diagnostics)

	api.ID = data.ID.ValueString()
	ok, _ = r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics)
	if !ok {
		return
	}

	api.toCantonParticipantNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonparticipantnodeserviceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CantonParticipantNodeServiceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("id"), &data.ID)...)

	var api ServiceAPIModel
	if ok, _ := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics); !ok {
		return
	}

	data.toCantonParticipantNodeServiceAPI(ctx, &api, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	if ok, _ := r.apiRequest(ctx, http.MethodPut, r.apiPath(&data), api, &api, &resp.Diagnostics); !ok {
		return
	}

	api.toCantonParticipantNodeServiceData(&data, &resp.Diagnostics)
	r.waitForReadyStatus(ctx, r.apiPath(&data), &resp.Diagnostics)

	if ok, _ := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics); !ok {
		return
	}
	api.toCantonParticipantNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonparticipantnodeserviceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CantonParticipantNodeServiceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	var api ServiceAPIModel
	api.ID = data.ID.ValueString()
	ok, status := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics, Allow404())
	if !ok {
		return
	}
	if status == 404 {
		resp.State.RemoveResource(ctx)
		return
	}

	api.toCantonParticipantNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonparticipantnodeserviceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CantonParticipantNodeServiceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	_, _ = r.apiRequest(ctx, http.MethodDelete, r.apiPath(&data), nil, nil, &resp.Diagnostics, Allow404())
	r.waitForRemoval(ctx, r.apiPath(&data), &resp.Diagnostics)
}
