// Code generated by eido. DO NOT EDIT.
// Copyright © Kaleido, Inc. 2025

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package platform

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CantonSuperValidatorNodeServiceResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Environment         types.String `tfsdk:"environment"`
	EnvironmentMemberID types.String `tfsdk:"environment_member_id"`
	Runtime             types.String `tfsdk:"runtime"`
	Name                types.String `tfsdk:"name"`
	StackID             types.String `tfsdk:"stack_id"`
	Defaultparty types.String `tfsdk:"defaultparty"`
	Kms          types.String `tfsdk:"kms"`
	Network      types.String `tfsdk:"network"`
	Nodekey      types.String `tfsdk:"nodekey"`
	Walletusers  types.String `tfsdk:"walletusers"`
	ForceDelete         types.Bool   `tfsdk:"force_delete"`
}

func CantonSuperValidatorNodeServiceResourceFactory() resource.Resource {
	return &cantonsupervalidatornodeserviceResource{}
}

type cantonsupervalidatornodeserviceResource struct {
	commonResource
}

func (r *cantonsupervalidatornodeserviceResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "kaleido_platform_cantonsupervalidatornode"
}

func (r *cantonsupervalidatornodeserviceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "",
		Attributes: map[string]schema.Attribute{
			"id": &schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"environment": &schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Environment ID where the CantonSuperValidatorNode service will be deployed",
			},
			"environment_member_id": &schema.StringAttribute{
				Computed: true,
			},
			"runtime": &schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Runtime ID where the CantonSuperValidatorNode service will be deployed",
			},
			"name": &schema.StringAttribute{
				Required:    true,
				Description: "Display name for the CantonSuperValidatorNode service",
			},
			"stack_id": &schema.StringAttribute{
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Description:   "Stack ID where the CantonSuperValidatorNode service belongs (optional)",
			},
			"defaultparty": &schema.StringAttribute{
				Optional:    true,
				Description: "Party Hint for the default party",
			},
			"kms": &schema.StringAttribute{
				Optional:    true,
				Description: "Configuration KMS for this canton node",
			},
			"network": &schema.StringAttribute{
				Optional:    true,
				Description: "CantonGlobalSynchronizerNetwork",
			},
			"nodekey": &schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "A base64 encoded secp256r1 private key for the node identity. The key will be generated if not set.",
			},
			"walletusers": &schema.StringAttribute{
				Optional:    true,
				Description: "A list of additional wallet users",
			},
			"force_delete": &schema.BoolAttribute{
				Optional:    true,
				Description: "Set to true when you plan to delete a protected CantonSuperValidatorNode service. You must apply this value before running terraform destroy.",
			},
		},
	}
}

func (data *CantonSuperValidatorNodeServiceResourceModel) toCantonSuperValidatorNodeServiceAPI(ctx context.Context, api *ServiceAPIModel, diagnostics *diag.Diagnostics) {
	api.Type = "CantonSuperValidatorNodeService"
	api.Name = data.Name.ValueString()
	api.StackID = data.StackID.ValueString()
	api.Runtime.ID = data.Runtime.ValueString()
	api.Config = make(map[string]interface{})

	if !data.Network.IsNull() && data.Network.ValueString() != "" {
		api.Config["network"] = data.Network.ValueString()
	}
	if !data.Defaultparty.IsNull() && data.Defaultparty.ValueString() != "" {
		api.Config["defaultParty"] = data.Defaultparty.ValueString()
	}
	// Handle Walletusers as JSON
	if !data.Walletusers.IsNull() && data.Walletusers.ValueString() != "" {
		var walletusersData interface{}
		err := json.Unmarshal([]byte(data.Walletusers.ValueString()), &walletusersData)
		if err != nil {
			diagnostics.AddAttributeError(
				path.Root("walletusers"),
				"Failed to parse Walletusers",
				err.Error(),
			)
		} else {
			api.Config["walletUsers"] = walletusersData
		}
	}
	if !data.Kms.IsNull() && data.Kms.ValueString() != "" {
		api.Config["kms"] = data.Kms.ValueString()
	}
	// Handle Nodekey credentials
	if !data.Nodekey.IsNull() && data.Nodekey.ValueString() != "" {
		if api.Credsets == nil {
			api.Credsets = make(map[string]*CredSetAPI)
		}
		api.Credsets["nodeKey"] = &CredSetAPI{
			Name: "nodeKey",
			Type: "key",
			Key: &CredSetKeyAPI{
				Value: data.Nodekey.ValueString(),
			},
		}
		api.Config["nodeKey"] = map[string]interface{}{
			"credSetRef": "nodeKey",
		}
	}
}

func (api *ServiceAPIModel) toCantonSuperValidatorNodeServiceData(data *CantonSuperValidatorNodeServiceResourceModel, diagnostics *diag.Diagnostics) {
	data.ID = types.StringValue(api.ID)
	data.EnvironmentMemberID = types.StringValue(api.EnvironmentMemberID)
	data.Runtime = types.StringValue(api.Runtime.ID)
	data.Name = types.StringValue(api.Name)
	data.StackID = types.StringValue(api.StackID)

	if v, ok := api.Config["network"].(string); ok {
		data.Network = types.StringValue(v)
	} else {
		data.Network = types.StringNull()
	}
	if v, ok := api.Config["defaultParty"].(string); ok {
		data.Defaultparty = types.StringValue(v)
	} else {
		data.Defaultparty = types.StringNull()
	}
	if walletusersData := api.Config["walletUsers"]; walletusersData != nil {
		if walletusersJSON, err := json.Marshal(walletusersData); err == nil {
			data.Walletusers = types.StringValue(string(walletusersJSON))
		} else {
			data.Walletusers = types.StringNull()
		}
	} else {
		data.Walletusers = types.StringNull()
	}
	if v, ok := api.Config["kms"].(string); ok {
		data.Kms = types.StringValue(v)
	} else {
		data.Kms = types.StringNull()
	}
	if credset, ok := api.Credsets["nodeKey"]; ok && credset.Key != nil {
		data.Nodekey = types.StringValue(credset.Key.Value)
	} else {
		data.Nodekey = types.StringNull()
	}
}

func (r *cantonsupervalidatornodeserviceResource) apiPath(data *CantonSuperValidatorNodeServiceResourceModel) string {
	path := fmt.Sprintf("/api/v1/environments/%s/services", data.Environment.ValueString())
	if data.ID.ValueString() != "" {
		path = path + "/" + data.ID.ValueString()
	}
	if !data.ForceDelete.IsNull() && data.ForceDelete.ValueBool() {
		path = path + "?force=true"
	}
	return path
}

func (r *cantonsupervalidatornodeserviceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CantonSuperValidatorNodeServiceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	var api ServiceAPIModel
	data.toCantonSuperValidatorNodeServiceAPI(ctx, &api, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	ok, _ := r.apiRequest(ctx, http.MethodPost, r.apiPath(&data), api, &api, &resp.Diagnostics)
	if !ok {
		return
	}

	api.toCantonSuperValidatorNodeServiceData(&data, &resp.Diagnostics)
	r.waitForReadyStatus(ctx, r.apiPath(&data), &resp.Diagnostics)

	api.ID = data.ID.ValueString()
	ok, _ = r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics)
	if !ok {
		return
	}

	api.toCantonSuperValidatorNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonsupervalidatornodeserviceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CantonSuperValidatorNodeServiceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("id"), &data.ID)...)

	var api ServiceAPIModel
	if ok, _ := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics); !ok {
		return
	}

	data.toCantonSuperValidatorNodeServiceAPI(ctx, &api, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	if ok, _ := r.apiRequest(ctx, http.MethodPut, r.apiPath(&data), api, &api, &resp.Diagnostics); !ok {
		return
	}

	api.toCantonSuperValidatorNodeServiceData(&data, &resp.Diagnostics)
	r.waitForReadyStatus(ctx, r.apiPath(&data), &resp.Diagnostics)

	if ok, _ := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics); !ok {
		return
	}
	api.toCantonSuperValidatorNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonsupervalidatornodeserviceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CantonSuperValidatorNodeServiceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	var api ServiceAPIModel
	api.ID = data.ID.ValueString()
	ok, status := r.apiRequest(ctx, http.MethodGet, r.apiPath(&data), nil, &api, &resp.Diagnostics, Allow404())
	if !ok {
		return
	}
	if status == 404 {
		resp.State.RemoveResource(ctx)
		return
	}

	api.toCantonSuperValidatorNodeServiceData(&data, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *cantonsupervalidatornodeserviceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CantonSuperValidatorNodeServiceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	_, _ = r.apiRequest(ctx, http.MethodDelete, r.apiPath(&data), nil, nil, &resp.Diagnostics, Allow404())
	r.waitForRemoval(ctx, r.apiPath(&data), &resp.Diagnostics)
}
