name: Go

on:
  push:
    branches: [master, v1.1]
  pull_request:
    branches: [master, v1.1]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'terraform-provider-kaleido'
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build and Test
        run: cd terraform-provider-kaleido && make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
